### PR TITLE
feat(explorer): add pager

### PR DESCRIPTION
**Pull request by plouc**

### CODE REVIEW

**Comment by plouc** [comment]
@rande, the build fail because of vault, do you know how I can fix this ? It's annoying because the explorer tests don't run

**Comment by rande** [comment]
I think the vault test should be skipped if aws credentials are not set.

**Comment by plouc** [comment]
@rande any idea on how to achieve this ?

**Comment by rande** [comment]
Give me 30min I will submit a patch ;)

**Comment by rande** [comment]
@plouc this commit should solve the problem: https://github.com/rande/gonode/commit/52aaef355fbfe59106e59f464262b8f981eefca0

**Comment by plouc** [comment]
@rande, build passed :)

**Pull request merged**
